#!/bin/bash

# check for root
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

export XPKG=/opt/xpkg
cd $XPKG/src/xpkg

xcodebuild >> $XPKG/log/xpkg.log 2>&1

rm -f $XPKG/core/xpkg
cp $XPKG/src/xpkg/build/Release/xpkg $XPKG/core/xpkg
ln -fF $XPKG/core/xpkg /usr/bin/xpkg
