# NAME
.SH NAME xpkg \- Advanced Package Management For Mac OS X

.SH SYNOPSIS Installs, removes and updates packages. It also allows the user to add third-party package sources.

.SH DESCRIPTION xpkg uses an sqlite3 database to manage all of its packages and repositories. This allows for dependancies to be calculated quickly and efficently. It also is incredibly easy to howt your own third party repository as they are just git submodules, added to /opt/xpkg/core/repos/

