#!/bin/sh

#  Script.sh
#  
#
#  Created by Jack Maloney on 4/2/14.
#

export XPKG=/opt/xpkg
export LOG=/opt/xpkg/log/xpkg.log

echo "Checking PATH..."
if [[ ":$PATH:" == *":/opt/xpkg/bin:"* ]]; then
  echo "bin PATH Looks Good"
else
  echo "Adding /opt/xpkg/bin to PATH"
  echo '# XPKG PATH SETUP' >> $HOME/.bash_profile
  echo 'export PATH=/opt/xpkg/bin:$PATH' >> $HOME/.bash_profile
  echo '# XPKG PATH SETUP END' >> $HOME/.bash_profile
fi

if [[ ":$PATH:" == *":/opt/xpkg/sbin:"* ]]; then
  echo "sbin PATH Looks Good"
else
  echo "Adding /opt/xpkg/sbin to PATH"
  echo '# XPKG PATH SETUP' >> $HOME/.bash_profile
  echo 'export PATH=/opt/xpkg/sbin:$PATH' >> $HOME/.bash_profile
  echo '# XPKG PATH SETUP END' >> $HOME/.bash_profile
fi

source $HOME/.bash_profile


mkdir -p $XPKG/log
mkdir -p $XPKG/bin
mkdir -p $XPKG/sbin
mkdir -p $XPKG/core
mkdir -p $XPKG/tmp
mkdir -p $XPKG/xpkgs
mkdir -p $XPKG/core/info/
cd $XPKG

echo "Downloading xpkg"
curl '-#' https://codeload.github.com/jmmaloney4/xpkg/zip/master > ./master.tar.gz
tar -xf ./master.tar.gz >> $LOG

echo "Downloading Git"
curl '-#L' https://codeload.github.com/git/git/tar.gz/v1.9.1 > ./git.tar.gz

echo "Downloading Autoconf"
curl '-#L' http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz > ./autoconf.tar.gz

echo "Downloading Automake"
curl '-#L' http://ftp.gnu.org/gnu/automake/automake-1.14.1.tar.gz > ./automake.tar.gz

echo "Unpacking Git"
tar -xf ./git.tar.gz >> $LOG

echo "Unpacking Autoconf"
tar -xf ./autoconf.tar.gz >> $LOG

echo "Unpacking Automake"
tar -xf ./automake.tar.gz >> $LOG

# Build Autoconf
echo "Building Autoconf"
mkdir -p /opt/xpkg/core/autoconf
cd ./autoconf-2.69/
./configure --prefix=/opt/xpkg/core/autoconf/
make
make install
cd /opt/xpkg/core/autoconf/
ln ./autoconf /opt/xpkg/

# Build Automake
echo "Building Automake"
mkdir -p /opt/xpkg/core/automake
cd ./automake-1.14.1/
./configure --prefix=/opt/xpkg/core/automake/
make
make install
cd /opt/xpkg/core/automake/
ln ./bin/* /opt/xpkg/bin/


# Build Git
cd $XPKG
cd ./git-1.9.1/

echo "Building Git, This May Take A Few Minutes"
sudo make configure >> $LOG
sudo mkdir -p $XPKG/core/git/1.9.1/
sudo ./configure --prefix=$XPKG/core/git/1.9.1/ >> $LOG
sudo make all >> $LOG
sudo make install >> $LOG

cd $XPKG/core/git/1.9.1/
sudo ln -fF ./bin/* $XPKG/bin/ >> $LOG

cd $XPKG >> $LOG

sudo $XPKG/bin/git init >> $LOG
sudo $XPKG/bin/git remote add origin https://github.com/jmmaloney4/xpkg.git >> $LOG
sudo $XPKG/bin/git pull origin master >> $LOG
sudo git branch --set-upstream-to=origin/master >> $LOG

cd $XPKG/src/xpkg >> $LOG

sudo xcodebuild >> $LOG

sudo cp $XPKG/src/xpkg/build/Release/xpkg $XPKG/core/

sudo ln -fF $XPKG/core/xpkg /usr/bin/xpkg

sudo /usr/bin/xpkg update
